# Generated by Django 4.1.13 on 2023-11-08 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component_Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SerialNumber', models.CharField(max_length=100)),
                ('PurchaseDate', models.DateField()),
                ('PurchasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SerialNumber', models.CharField(max_length=100)),
                ('ProductionDate', models.DateField(default=datetime.datetime.today)),
                ('WarrantyExpirationDate', models.DateField()),
                ('Components', models.ManyToManyField(blank=True, to='app.components')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('PostalCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(max_length=100)),
                ('ProductionDate', models.DateField(default=datetime.datetime.today)),
                ('Components', models.ManyToManyField(blank=True, to='app.component_equipment')),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipments')),
                ('Labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labor')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderDate', models.DateField(default=datetime.datetime.today)),
                ('Status', models.BooleanField(default=False)),
                ('Costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
                ('Equipments', models.ManyToManyField(blank=True, to='app.equipments')),
            ],
        ),
        migrations.AddField(
            model_name='labor',
            name='LaborType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labortype'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='EquipmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipmenttype'),
        ),
        migrations.AddField(
            model_name='components',
            name='ComponentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.componenttype'),
        ),
        migrations.AddField(
            model_name='components',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='component_equipment',
            name='Component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.components'),
        ),
        migrations.AddField(
            model_name='component_equipment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipments'),
        ),
    ]
