# Generated by Django 4.1.12 on 2023-11-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
