# Generated by Django 4.1.13 on 2023-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
