# Generated by Django 4.1.13 on 2023-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='supplier',
            name='warehouse',
            field=models.ManyToManyField(to='app.warehouse'),
        ),
    ]
