# Generated by Django 4.1.13 on 2023-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_supplier_warehouse_supplier_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='components_purchase',
            fields=[
                ('components_purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(to='app.components')),
            ],
        ),
    ]
